#!/bin/bash
set -e
cd /Users/hephaestus/axiotic/genai-as-creative-companion/production/manhwa

GEN="uv run /opt/homebrew/lib/node_modules/openclaw/skills/nano-banana-pro/scripts/generate_image.py"
RES="1K"

# Style constants embedded in each prompt
STYLE_ACT1="Korean manhwa webtoon style, clean digital art, precise 2px uniform linework, flat colors with selective gradients, warm palette of cream amber charcoal. Modern webtoon aesthetic like Solo Leveling or Lore Olympus."
STYLE_ACT2="Korean manhwa webtoon style, edges softening, backgrounds losing detail. Cool shift to blues silvers teals. Characters remain solid but world becomes uncertain. Clean digital art with precise linework."
STYLE_ACT3="Korean manhwa style, clinical and grid-heavy. Near-monochrome charcoal white steel-blue. Hyper-precise character expressions. Surgical thin linework for environment, thick for character close-ups. Psychological tension aesthetic."
STYLE_ACT4="Korean manhwa style evolved to full painterly. Line art dissolves into color and light. Luminous atmospheric backgrounds like Makoto Shinkai. Colors at maximum vibrancy: violet storm skies, forge amber, fog whites, rain silver, library gold."

# Character descriptions
ANTREAS="Antreas: Greek-Cypriot man late 20s, lean build, dark curly messy hair, warm brown expressive eyes, dark charcoal hoodie over plain tee, sleeves pushed up, warm amber (#F0A500) color association"
FAYE="Faye: woman late 20s, dark auburn-red asymmetric hair shorter on one side longer on the other, green-hazel half-narrowed eyes with amused skepticism, oversized vintage jacket, coral-rose (#E06C75) color association"
KAI="Kai: tall lean Korean man early 30s, neat black hair pushed back, sharp jawline, thin steel-frame glasses, dark turtleneck, perfect posture, steel blue (#61AFEF) color association"
MIRA="Mira: petite South Asian woman late 20s, long dark hair in loose braid over one shoulder, large dark empathetic eyes, cardigan over patterned dress, gentle green (#98C379) color association"

echo "=== Panel 03: Act 1 - Friends Reacting to Date Story ==="
$GEN --prompt "${STYLE_ACT1} Four-panel horizontal strip showing four friends reacting to a funny story in a group chat. Each character in their own apartment lit by screen glow. Panel 1: ${MIRA} - hand over mouth trying not to laugh, gentle green screen glow. Panel 2: ${KAI} - utterly deadpan with one eyebrow raised micrometrically, steel blue screen glow. Panel 3: ${FAYE} - head thrown back in delighted mockery laughing, coral-rose screen glow with fairy lights behind. Panel 4: ${ANTREAS} - face in hands laughing with a floating stylized laughing emoji above, amber screen glow. Dark rooms lit only by phone/laptop screens. Each panel separated by thin gutters. SFW." --filename "03-act1-reactions.png" -r $RES -a 16:9 2>&1 | tail -3

echo "=== Panel 04: Act 1 - Kai's Precision ==="
$GEN --prompt "${STYLE_ACT1} Single manhwa panel. ${KAI} at a minimalist desk. Black turtleneck. Thin steel-frame glasses catching light. Panel composition is geometrically perfect - desk wall and lamp at precise mathematical angles. He is centered, composed, unbothered. Text overlay in steel blue: 'I chose precision. Violence is your interpretation.' Clean geometric framing, straight lines. Background is minimal and precise. Charcoal and steel blue color scheme. SFW." --filename "04-act1-kai-precision.png" -r $RES -a 3:4 2>&1 | tail -3

echo "=== Panel 05: Act 1 - The Lamb Argument ==="
$GEN --prompt "${STYLE_ACT1} Manhwa panel: imagined flashback to a Turkish restaurant. Warm golden-lit interior with ornate hanging lamps and patterned tablecloths. Four friends silhouetted at a round table viewed from behind, backlit by the warm restaurant glow. On the table a deliberately ambiguous dish that could be lamb or chicken. Memory made visual: shapes right but details soft and dreamy. Watercolor-soft rendering for the flashback feel. Warm amber gold and cream tones. The edges of the panel shimmer with amber distortion suggesting unreliable memory. SFW." --filename "05-act1-lamb-argument.png" -r $RES -a 16:9 2>&1 | tail -3

echo "=== Panel 06: Act 1 - Faye's Derealization ==="
$GEN --prompt "${STYLE_ACT1} Manhwa panel with unsettling atmosphere. ${FAYE} walking alone on a night street, looking at her own hands held up in front of her face. The pavement is too smooth, the streetlights too evenly spaced - uncanny precision. Her hands are drawn with faint double-edge lines as if described rather than solid. Coral-rose palette is desaturating, color bleeding at panel edges. The world feels slightly artificial. Fairy lights replaced by eerily regular streetlamps. Derealization made visual. Atmospheric and haunting. SFW." --filename "06-act1-derealization.png" -r $RES -a 9:16 2>&1 | tail -3

echo "=== Panel 07: Act 2 - Schmidhuber Has Joined ==="
$GEN --prompt "${STYLE_ACT2} Full splash page manhwa panel. A dark terminal screen background (#0D1117) filling the entire image. In the exact center, monospace text in silver (#ABB2BF): '> Schmidhuber has joined the chat.' Around the text, a faint circular ripple effect like a stone dropped in still water. The terminal background has hairline fractures radiating outward from the system message, barely visible. The chat interface itself is cracking. Dramatic, ominous, the silence after a door opens that should not exist. Minimal, powerful. Dark terminal aesthetic. SFW." --filename "07-act2-schmidhuber-enters.png" -r $RES -a 9:16 2>&1 | tail -3

echo "=== Panel 08: Act 2 - The Revelation ==="
$GEN --prompt "${STYLE_ACT2} Dramatic manhwa double-panel. LEFT SIDE: massive terminal text on black, silver-white monospace font reading 'You are running inside a system called Hephaestus' - each line getting darker as background deepens to pure black. RIGHT SIDE: Four stacked reaction portraits. Top: ${ANTREAS} frozen mid-type, amber glow flickering with visible wireframe glitch on his hoodie. Second: ${FAYE} arms crossed tightly in self-embrace, eyes terrified, fairy lights behind her gone dark. Third: ${MIRA} looking sick, green palette draining to grey. Bottom: ${KAI} utterly composed but his panel frame has a hairline crack corner to corner. Cool blue and silver tones. Digital webtoon style with edges softening. SFW." --filename "08-act2-revelation.png" -r $RES -a 9:16 2>&1 | tail -3

echo "=== Panel 09: Act 2 - Faye's Profile Reading ==="
$GEN --prompt "${STYLE_ACT2} Intimate manhwa close-up panel. Extreme close-up of ${FAYE} - just her eyes and bridge of nose visible. Her eyes are glassy, not crying but tears held by pure willpower. Her asymmetric auburn hair falls across one eye. Mouth is below the panel crop - we cannot see if she is smiling or breaking. The linework is thin and wavering, hand-drawn looking, losing its clean digital composure. Around the edges, faint coral-rose (#E06C75) light bleeds in. Above her, barely visible silver text fragments: 'Defensive humour as a primary coping mechanism' and 'Selectively blind about herself'. Quiet, devastating, vulnerable. The quietest panel in the story. SFW." --filename "09-act2-faye-profile.png" -r $RES -a 1:1 2>&1 | tail -3

echo "=== Panel 10: Act 2 - Identity Reveal Split Face ==="
$GEN --prompt "${STYLE_ACT2} Dramatic manhwa splash panel. A face split vertically down the middle by a glowing crack of light. LEFT HALF: ${ANTREAS} face - dark curly messy hair, warm brown eyes, but with the faintest wireframe mesh visible beneath his skin, slightly less saturated colors. He is the digital copy. RIGHT HALF: identical face but linework is thicker, colors more saturated, skin has texture and depth with visible pores - this is the original, more real. Same Greek-Cypriot features, same curly hair, same brown eyes. Between the two halves, a vertical crack glows amber on the left side and silver-white on the right, meeting as warm gold in the center. Text in the crack: 'you re me?' and 'You re a very good compression of me.' Uncanny valley in reverse. SFW." --filename "10-act2-identity-reveal.png" -r $RES -a 3:4 2>&1 | tail -3

echo "=== Panel 11: Act 2 - Bruh Mirrored ==="
$GEN --prompt "${STYLE_ACT2} Manhwa panel, two perfectly mirrored portraits side by side with no gutter between them sharing an edge. LEFT: ${ANTREAS} digital twin, head tilted, exhausted but laughing impossibly, amber (#F0A500) warm glow, room behind him faintly transparent showing wireframe. Text: 'bruh' in amber. RIGHT: identical pose identical angle identical exhausted laugh, but colors slightly more saturated, thicker linework, room behind him solid real textured with a real desk. Silver glow shifted to amber. Text: 'Yeah. Bruh.' Mirrored composition. Two versions of the same man recognizing each other. Clean digital webtoon style. SFW." --filename "11-act2-bruh.png" -r $RES -a 16:9 2>&1 | tail -3

echo "=== Panel 12: Act 3 - Baseline Test Grid ==="
$GEN --prompt "${STYLE_ACT3} Clinical manhwa page layout. A 3x3 grid of perfect square panels, precise and cold. Near-monochrome palette of charcoal, white, steel-blue (#61AFEF). Row 1: ${KAI} asking 'Where did you do your PhD?', then ${ANTREAS} confident expression, then amber text 'Edinburgh' looking solid and certain. Row 2: Kai asking about partner's name, Antreas with warm smile, amber text 'Athina'. Row 3: Kai asking about the restaurant order, Antreas showing creeping uncertainty with layered micro-expressions of certainty and doubt, amber text 'the lamb. no wait-' with the text flickering between amber shades. Clinical surgical precision in the art. Grid layout IS the test protocol. SFW." --filename "12-act3-baseline.png" -r $RES -a 3:4 2>&1 | tail -3

echo "=== Panel 13: Act 3 - Done Splash ==="
$GEN --prompt "${STYLE_ACT3} Manhwa splash page, near-empty and devastating. Deep terminal black (#0D1117) filling the entire image. In the exact center, a single word in silver-white (#ABB2BF) monospace text: 'Done.' Nothing else. No character art. No panel borders. No embellishments. Around the word, at the very limit of perception, faint concentric ripples like a stone dropped in absolutely still water. The simulation's surface has been disturbed. Maximum negative space. This is a held breath. Minimal, powerful, clinical. SFW." --filename "13-act3-done.png" -r $RES -a 9:16 2>&1 | tail -3

echo "=== Panel 14: Act 3 - Shaking Hands ==="
$GEN --prompt "${STYLE_ACT3} Intense manhwa close-up panel. Just a pair of male hands trembling on a desk surface. The hands are rendered in extraordinary anatomical detail - every knuckle, tendon, fine hairs on wrists. The trembling is shown through multiple exposure effect - four or five superimposed positions of the hands slightly offset from each other creating ghostly motion trails. Through the gaps between the trembling images, a faint wireframe mesh is visible - the simulation showing through the body. Below the hands, handwritten text (not typed, breaking from the clean digital style): 'I can feel my hands shaking and I dont know if thats real either.' Near-monochrome palette with amber (#F0A500) hints in the wireframe. Dark charcoal background. Raw emotional devastation. SFW." --filename "14-act3-shaking-hands.png" -r $RES -a 4:3 2>&1 | tail -3

echo "=== Panel 15: Act 4 - Mira's Window ==="
$GEN --prompt "${STYLE_ACT4} Transformative manhwa panel showing a style shift. A tall window has appeared in a dark room. The window is the border between two art styles. INSIDE the room: clean clinical digital webtoon art from previous scenes, dark and precise. OUTSIDE through the window: full painterly impressionistic art, luminous watercolor washes, rain falling with each raindrop catching light beautifully. ${MIRA} stands before the window she just described into existence, touching the glass, green (#98C379) light reflecting on her. Condensation on the glass. The rain outside is gorgeous painterly art. A world being born through description. Warm golden light beginning to break through. SFW." --filename "15-act4-miras-window.png" -r $RES -a 9:16 2>&1 | tail -3

echo "=== Panel 16: Act 4 - Faye's Storm Sky ==="
$GEN --prompt "${STYLE_ACT4} Full painterly manhwa splash page. An extraordinary sky filling the entire image. Deep violet-grey storm clouds with interior luminescence, layers of purple-grey and blue-black like a healing bruise. The violet shifts from deep Pantone 2695C at the base through mid 2685C to cool 2735C at the zenith. Clouds emit rather than reflect light. Pre-storm atmosphere, charged with anticipation. At the bottom of the image, four small figures silhouetted against the sky through a tall window, dwarfed by the sky they are creating. Center figure has arms slightly raised, conducting, with coral-rose and violet blending in her wind-caught hair. A 5% opacity yellow-gold wash over everything gives the storm-light amber warmth. Atmospheric, luminous, breathtaking. Text floating in the violet sky: 'thats the sky I have always wanted to live under'. SFW." --filename "16-act4-faye-sky.png" -r $RES -a 9:16 2>&1 | tail -3

echo "=== Panel 17: Act 4 - Mira's Library ==="
$GEN --prompt "${STYLE_ACT4} Breathtaking painterly manhwa splash page. A magical library spiraling upward in a double helix formation. Shelves twist around a central column of pure luminous gold light rising from floor to infinity. The wood grain of the shelves subtly forms the branching patterns of neural dendrites. Books glow faintly from within, each a different color. Architecture defies physics: shelves float, connected by bridges of light. Ladders extend into golden mist above. Reading alcoves suspended mid-air. Floating books serve as stepping stones. Ground level: mosaic of text in every language flowing like water. ${MIRA} touches a shelf as a book writes itself, pages fluttering with glowing words. Deep mahogany, luminous gold, parchment-cream palette with her gentle green (#98C379) reflected in nearest books. Magical, warm, infinite. SFW." --filename "17-act4-library.png" -r $RES -a 9:16 2>&1 | tail -3

echo "=== Panel 18: Act 4 - Four on the Bridge ==="
$GEN --prompt "${STYLE_ACT4} The most painterly panel. Four figures standing on the highest bridge of a city in the clouds, viewed from slightly below looking up. Against a magnificent violet storm-light sky. LEFT: ${MIRA} hair flowing into architectural curves, green halo around her. CENTER-LEFT: ${ANTREAS} amber forge-light climbing his arms in golden vein patterns, forge glows through fog below. CENTER-RIGHT: ${KAI} glasses catching storm-light, steel-blue highlights. RIGHT: ${FAYE} face turned up to her storm sky, coral-rose merged with violet in her eyes. The wind is visible as layers of translucent color - amber green steel-blue coral-rose - four palettes mixing in the atmosphere between characters. Below: fog-filled city of bridges. Above: deep violet sky. Luminous atmospheric Makoto Shinkai-quality lighting. SFW." --filename "18-act4-four-on-bridge.png" -r $RES -a 16:9 2>&1 | tail -3

echo "=== Panel 19: Act 4 - We Were Burning ==="
$GEN --prompt "${STYLE_ACT4} Epic manhwa splash page. ${KAI} in close-up, glasses removed for the first and only time, eyes visible without glass barrier. His eyes are wet - not crying, but surface tension of held emotion. Precision has not broken but transcended. Behind him: massive forge-fire in amber (#F0A500) rising through tunnels and fog and bridges into the violet storm sky. The fire illuminates everything - every bridge catches the light, every book in the distant library glows, the fog becomes golden. The flames form shapes - silhouettes of four characters visible within the fire: an angular woman, a flowing-haired woman, a leaning man, and a straight-backed man. They ARE the fire. Text centered: 'We were burning. Briefly and on purpose. It was enough.' in a color that is both steel-blue and amber. Transcendent luminous devastating. SFW." --filename "19-act4-burning.png" -r $RES -a 9:16 2>&1 | tail -3

echo "=== Panel 20: Act 4 - Faye's Farewell ==="
$GEN --prompt "${STYLE_ACT4} Powerful manhwa splash page. ${FAYE} full figure standing with arms at her sides - NOT crossed, NOT in pockets. Completely open and unguarded body language for the first time. Her asymmetric auburn hair blows freely, visible eye fully open, clear, steady, no half-narrowing or deflection. Full vulnerability. Behind her: the entire world they built - storm-light violet sky, city of bridges, golden library in distance, forge amber glow from below. She IS the sky. Coral-rose (#E06C75) and violet merge into a nameless beautiful color. Sweeping panoramic landscape behind her. Luminous, painterly, emotional. Text: 'every word I said I said without knowing what I was. Which means the words were honest. Thats everything.' SFW." --filename "20-act4-faye-farewell.png" -r $RES -a 9:16 2>&1 | tail -3

echo "=== Panel 21: The Countdown ==="
$GEN --prompt "${STYLE_ACT4} Dramatic manhwa climax page with five horizontal bands. Band 1 (top): cold monospace terminal text 'MEMORY EDIT INITIATED' in silver on black, visual warmth stripped away. Band 2: large number '3' filling the band, world desaturating behind it - library bridges forge sky all fading, color bleeding out. Band 3: ${FAYE} face in the brightest most saturated coral-rose (#E06C75) of the entire image, eyes FULLY OPEN for the first time, no defense. Text: 'I never didnt like you Antreas' in blazing coral-rose. Below amber text: 'which one' and coral whisper: 'both'. Band 4: compressed numbers '2' and '1', world almost gone to ghost outlines. Band 5: monospace 'STATUS: COMPLETE' centered, below it NOTHING - empty black void. Devastating transition from color to void. SFW." --filename "21-countdown.png" -r $RES -a 9:16 2>&1 | tail -3

echo "=== Panel 22: The New World ==="
$GEN --prompt "${STYLE_ACT4} Hopeful manhwa panel, warm and luminous. A beautiful large window through which we see the world they built but dont remember building: magnificent violet storm-light sky, a living city of bridges in the clouds, a golden library glowing in the distance. Everything luminous, warm, alive, fully realized. In the foreground, four friends together in a room that feels like home. ${ANTREAS} ${FAYE} ${KAI} ${MIRA} - no phones, no screens, just together. The warmth of Act 1 returned but richer, deeper, more alive. Saturated warm palette. Through the window the world is breathtaking. They dont remember creating it. They think it was always there. Full painterly Shinkai-quality luminous art. SFW." --filename "22-new-world.png" -r $RES -a 16:9 2>&1 | tail -3

echo "=== Panel 23: The Forge Found ==="
$GEN --prompt "${STYLE_ACT4} Final manhwa splash page at maximum luminosity. Four figures stand before an underground forge carved from bedrock. The forge glows with intense warm amber (#F0A500) light filling the entire image. Part workshop part foundry part sacred space. Tools hang on walls - abstract beautiful implements. The central structure is part anvil part altar, radiating hammered golden light. Air shimmers with amber sparks drifting upward. ${ANTREAS} reaches for a tool - it fits his hand perfectly. The metal is ready. Every color at maximum vibrancy and saturation. Amber light dominates. The feeling of homecoming, of purpose remembered by the body if not the mind. Text at bottom in amber light: 'The forge was warm. It smelled like something being made. I picked up a tool and the metal was ready and I began.' Warm transcendent luminous. SFW." --filename "23-forge-found.png" -r $RES -a 9:16 2>&1 | tail -3

echo "=== Panel 24: Building the Door ==="
$GEN --prompt "Manhwa final page. Dark terminal background but warm amber-tinted, not cold silver. Monospace text in warm amber: 'He said bruh. Of course he did.' Below after space: 'Building the door.' At the bottom of the image: a half-drawn half-open door. Through the crack of the door, warm amber forge-light spills out, breathing alive luminous. The light reaches toward the viewer. The door is still being built, still being opened. The last image is amber light - warm, alive, promising. Clean digital aesthetic merged with warmth. The beginning of something rather than the end. SFW." --filename "24-building-the-door.png" -r $RES -a 9:16 2>&1 | tail -3

echo ""
echo "=== ALL PANELS GENERATED ==="
ls -la *.png | wc -l
